// stm32h7xx_extra.h
// PUBLIC DOMAIN
// https://www.purposeful.co.uk/goodmicro/

/*
  I, Tom Vajzovic, am the author of this software and its documentation.
  I permanently abandon all copyright and other intellectual property rights
  in them.

  I am fairly certain that the software does what the documentation says it
  does, but I do not guarantee that it does, or that it does what you think it
  should.  I do not guarantee that it will not have undesirable side effects.

  If you use, modify or distribute this software then you do so at your own
  risk.  If you do not pass on this warning then you may be responsible for any
  problems encountered by those who obtain the software through you.
*/

#ifndef STM32H7XX_EXTRA_H_INCLUDED
#define STM32H7XX_EXTRA_H_INCLUDED

#define DMA_SxCR_PL_LOW             (0 << DMA_SxCR_PL_Pos)
#define DMA_SxCR_PL_MEDIUM          (1 << DMA_SxCR_PL_Pos)
#define DMA_SxCR_PL_HIGH            (2 << DMA_SxCR_PL_Pos)
#define DMA_SxCR_PL_VHIGH           (3 << DMA_SxCR_PL_Pos)

#define DMA_SxCR_MSIZE_8BIT         (0 << DMA_SxCR_MSIZE_Pos)
#define DMA_SxCR_MSIZE_16BIT        (1 << DMA_SxCR_MSIZE_Pos)
#define DMA_SxCR_MSIZE_32BIT        (2 << DMA_SxCR_MSIZE_Pos)

#define DMA_SxCR_PSIZE_8BIT         (0 << DMA_SxCR_PSIZE_Pos)
#define DMA_SxCR_PSIZE_16BIT        (1 << DMA_SxCR_PSIZE_Pos)
#define DMA_SxCR_PSIZE_32BIT        (2 << DMA_SxCR_PSIZE_Pos)

#define DMA_SxCR_DIR_P2M            (0 << DMA_SxCR_DIR_Pos)
#define DMA_SxCR_DIR_M2P            (1 << DMA_SxCR_DIR_Pos)
#define DMA_SxCR_DIR_M2M            (2 << DMA_SxCR_DIR_Pos)

#define DMA_LISR_ALLIF0     (DMA_LISR_TCIF0 | DMA_LISR_HTIF0 | DMA_LISR_TEIF0 | DMA_LISR_DMEIF0 | DMA_LISR_FEIF0)
#define DMA_LISR_ALLIF1     (DMA_LISR_TCIF1 | DMA_LISR_HTIF1 | DMA_LISR_TEIF1 | DMA_LISR_DMEIF1 | DMA_LISR_FEIF1)
#define DMA_LISR_ALLIF2     (DMA_LISR_TCIF2 | DMA_LISR_HTIF2 | DMA_LISR_TEIF2 | DMA_LISR_DMEIF2 | DMA_LISR_FEIF2)
#define DMA_LISR_ALLIF3     (DMA_LISR_TCIF3 | DMA_LISR_HTIF3 | DMA_LISR_TEIF3 | DMA_LISR_DMEIF3 | DMA_LISR_FEIF3)
#define DMA_HISR_ALLIF4     (DMA_HISR_TCIF4 | DMA_HISR_HTIF4 | DMA_HISR_TEIF4 | DMA_HISR_DMEIF4 | DMA_HISR_FEIF4)
#define DMA_HISR_ALLIF5     (DMA_HISR_TCIF5 | DMA_HISR_HTIF5 | DMA_HISR_TEIF5 | DMA_HISR_DMEIF5 | DMA_HISR_FEIF5)
#define DMA_HISR_ALLIF6     (DMA_HISR_TCIF6 | DMA_HISR_HTIF6 | DMA_HISR_TEIF6 | DMA_HISR_DMEIF6 | DMA_HISR_FEIF6)
#define DMA_HISR_ALLIF7     (DMA_HISR_TCIF7 | DMA_HISR_HTIF7 | DMA_HISR_TEIF7 | DMA_HISR_DMEIF7 | DMA_HISR_FEIF7)

#define DMA_LIFCR_CALLIF0   (DMA_LIFCR_CTCIF0 | DMA_LIFCR_CHTIF0 | DMA_LIFCR_CTEIF0 | DMA_LIFCR_CDMEIF0 | DMA_LIFCR_CFEIF0)
#define DMA_LIFCR_CALLIF1   (DMA_LIFCR_CTCIF1 | DMA_LIFCR_CHTIF1 | DMA_LIFCR_CTEIF1 | DMA_LIFCR_CDMEIF1 | DMA_LIFCR_CFEIF1)
#define DMA_LIFCR_CALLIF2   (DMA_LIFCR_CTCIF2 | DMA_LIFCR_CHTIF2 | DMA_LIFCR_CTEIF2 | DMA_LIFCR_CDMEIF2 | DMA_LIFCR_CFEIF2)
#define DMA_LIFCR_CALLIF3   (DMA_LIFCR_CTCIF3 | DMA_LIFCR_CHTIF3 | DMA_LIFCR_CTEIF3 | DMA_LIFCR_CDMEIF3 | DMA_LIFCR_CFEIF3)
#define DMA_HIFCR_CALLIF4   (DMA_HIFCR_CTCIF4 | DMA_HIFCR_CHTIF4 | DMA_HIFCR_CTEIF4 | DMA_HIFCR_CDMEIF4 | DMA_HIFCR_CFEIF4)
#define DMA_HIFCR_CALLIF5   (DMA_HIFCR_CTCIF5 | DMA_HIFCR_CHTIF5 | DMA_HIFCR_CTEIF5 | DMA_HIFCR_CDMEIF5 | DMA_HIFCR_CFEIF5)
#define DMA_HIFCR_CALLIF6   (DMA_HIFCR_CTCIF6 | DMA_HIFCR_CHTIF6 | DMA_HIFCR_CTEIF6 | DMA_HIFCR_CDMEIF6 | DMA_HIFCR_CFEIF6)
#define DMA_HIFCR_CALLIF7   (DMA_HIFCR_CTCIF7 | DMA_HIFCR_CHTIF7 | DMA_HIFCR_CTEIF7 | DMA_HIFCR_CDMEIF7 | DMA_HIFCR_CFEIF7)

#define DMAMUX1_CCR_DMAREQ_ID_DMAMUX1_REQ_GEN0    1
#define DMAMUX1_CCR_DMAREQ_ID_DMAMUX1_REQ_GEN1    2
#define DMAMUX1_CCR_DMAREQ_ID_DMAMUX1_REQ_GEN2    3
#define DMAMUX1_CCR_DMAREQ_ID_DMAMUX1_REQ_GEN3    4
#define DMAMUX1_CCR_DMAREQ_ID_DMAMUX1_REQ_GEN4    5
#define DMAMUX1_CCR_DMAREQ_ID_DMAMUX1_REQ_GEN5    6
#define DMAMUX1_CCR_DMAREQ_ID_DMAMUX1_REQ_GEN6    7
#define DMAMUX1_CCR_DMAREQ_ID_DMAMUX1_REQ_GEN7    8
#define DMAMUX1_CCR_DMAREQ_ID_ADC1                9
#define DMAMUX1_CCR_DMAREQ_ID_ADC2               10
#define DMAMUX1_CCR_DMAREQ_ID_TIM1_CH1           11
#define DMAMUX1_CCR_DMAREQ_ID_TIM1_CH2           12
#define DMAMUX1_CCR_DMAREQ_ID_TIM1_CH3           13
#define DMAMUX1_CCR_DMAREQ_ID_TIM1_CH4           14
#define DMAMUX1_CCR_DMAREQ_ID_TIM1_UP            15
#define DMAMUX1_CCR_DMAREQ_ID_TIM1_TRIG          16
#define DMAMUX1_CCR_DMAREQ_ID_TIM1_COM           17
#define DMAMUX1_CCR_DMAREQ_ID_TIM2_CH1           18
#define DMAMUX1_CCR_DMAREQ_ID_TIM2_CH2           19
#define DMAMUX1_CCR_DMAREQ_ID_TIM2_CH3           20
#define DMAMUX1_CCR_DMAREQ_ID_TIM2_CH4           21
#define DMAMUX1_CCR_DMAREQ_ID_TIM2_UP            22
#define DMAMUX1_CCR_DMAREQ_ID_TIM3_CH1           23
#define DMAMUX1_CCR_DMAREQ_ID_TIM3_CH2           24
#define DMAMUX1_CCR_DMAREQ_ID_TIM3_CH3           25
#define DMAMUX1_CCR_DMAREQ_ID_TIM3_CH4           26
#define DMAMUX1_CCR_DMAREQ_ID_TIM3_UP            27
#define DMAMUX1_CCR_DMAREQ_ID_TIM3_TRIG          28
#define DMAMUX1_CCR_DMAREQ_ID_TIM4_CH1           29
#define DMAMUX1_CCR_DMAREQ_ID_TIM4_CH2           30
#define DMAMUX1_CCR_DMAREQ_ID_TIM4_CH3           31
#define DMAMUX1_CCR_DMAREQ_ID_TIM4_UP            32
#define DMAMUX1_CCR_DMAREQ_ID_I2C1_RX            33
#define DMAMUX1_CCR_DMAREQ_ID_I2C1_TX            34
#define DMAMUX1_CCR_DMAREQ_ID_I2C2_RX            35
#define DMAMUX1_CCR_DMAREQ_ID_I2C2_TX            36
#define DMAMUX1_CCR_DMAREQ_ID_SPI1_RX            37
#define DMAMUX1_CCR_DMAREQ_ID_SPI1_TX            38
#define DMAMUX1_CCR_DMAREQ_ID_SPI2_RX            39
#define DMAMUX1_CCR_DMAREQ_ID_SPI2_TX            40
#define DMAMUX1_CCR_DMAREQ_ID_USART1_RX          41
#define DMAMUX1_CCR_DMAREQ_ID_USART1_TX          42
#define DMAMUX1_CCR_DMAREQ_ID_USART2_RX          43
#define DMAMUX1_CCR_DMAREQ_ID_USART2_TX          44
#define DMAMUX1_CCR_DMAREQ_ID_USART3_RX          45
#define DMAMUX1_CCR_DMAREQ_ID_USART3_TX          46
#define DMAMUX1_CCR_DMAREQ_ID_TIM8_CH1           47
#define DMAMUX1_CCR_DMAREQ_ID_TIM8_CH2           48
#define DMAMUX1_CCR_DMAREQ_ID_TIM8_CH3           49
#define DMAMUX1_CCR_DMAREQ_ID_TIM8_CH4           50
#define DMAMUX1_CCR_DMAREQ_ID_TIM8_UP            51
#define DMAMUX1_CCR_DMAREQ_ID_TIM8_TRIG          52
#define DMAMUX1_CCR_DMAREQ_ID_TIM8_COM           53
#define DMAMUX1_CCR_DMAREQ_ID_TIM5_CH1           55
#define DMAMUX1_CCR_DMAREQ_ID_TIM5_CH2           56
#define DMAMUX1_CCR_DMAREQ_ID_TIM5_CH3           57
#define DMAMUX1_CCR_DMAREQ_ID_TIM5_CH4           58
#define DMAMUX1_CCR_DMAREQ_ID_TIM5_UP            59
#define DMAMUX1_CCR_DMAREQ_ID_TIM5_TRIG          60
#define DMAMUX1_CCR_DMAREQ_ID_SPI3_RX            61
#define DMAMUX1_CCR_DMAREQ_ID_SPI3_TX            62
#define DMAMUX1_CCR_DMAREQ_ID_UART4_RX           63
#define DMAMUX1_CCR_DMAREQ_ID_UART4_TX           64
#define DMAMUX1_CCR_DMAREQ_ID_UART5_RX           65
#define DMAMUX1_CCR_DMAREQ_ID_UART5_TX           66
#define DMAMUX1_CCR_DMAREQ_ID_DAC_CH1            67
#define DMAMUX1_CCR_DMAREQ_ID_DAC_CH2            68
#define DMAMUX1_CCR_DMAREQ_ID_TIM6_UP            69
#define DMAMUX1_CCR_DMAREQ_ID_TIM7_UP            70
#define DMAMUX1_CCR_DMAREQ_ID_USART6_RX          71
#define DMAMUX1_CCR_DMAREQ_ID_USART6_TX          72
#define DMAMUX1_CCR_DMAREQ_ID_I2C3_RX            73
#define DMAMUX1_CCR_DMAREQ_ID_I2C3_TX            74
#define DMAMUX1_CCR_DMAREQ_ID_DCMI               75
#define DMAMUX1_CCR_DMAREQ_ID_CRYP_IN            76
#define DMAMUX1_CCR_DMAREQ_ID_CRYP_OUT           77
#define DMAMUX1_CCR_DMAREQ_ID_HASH_IN            78
#define DMAMUX1_CCR_DMAREQ_ID_UART7_RX           79
#define DMAMUX1_CCR_DMAREQ_ID_UART7_TX           80
#define DMAMUX1_CCR_DMAREQ_ID_UART8_RX           81
#define DMAMUX1_CCR_DMAREQ_ID_UART8_TX           82
#define DMAMUX1_CCR_DMAREQ_ID_SPI4_RX            83
#define DMAMUX1_CCR_DMAREQ_ID_SPI4_TX            84
#define DMAMUX1_CCR_DMAREQ_ID_SPI5_RX            85
#define DMAMUX1_CCR_DMAREQ_ID_SPI5_TX            86
#define DMAMUX1_CCR_DMAREQ_ID_SAI1A              87
#define DMAMUX1_CCR_DMAREQ_ID_SAI1B              88
#define DMAMUX1_CCR_DMAREQ_ID_SAI2A              89
#define DMAMUX1_CCR_DMAREQ_ID_SAI2B              90
#define DMAMUX1_CCR_DMAREQ_ID_SWPMI_RX           91
#define DMAMUX1_CCR_DMAREQ_ID_SWPMI_TX           92
#define DMAMUX1_CCR_DMAREQ_ID_SPDIFRX_DAT        93
#define DMAMUX1_CCR_DMAREQ_ID_SPDIFRX_CTRL       94
#define DMAMUX1_CCR_DMAREQ_ID_HR_REQ1            95
#define DMAMUX1_CCR_DMAREQ_ID_HR_REQ2            96
#define DMAMUX1_CCR_DMAREQ_ID_HR_REQ3            97
#define DMAMUX1_CCR_DMAREQ_ID_HR_REQ4            98
#define DMAMUX1_CCR_DMAREQ_ID_HR_REQ5            99
#define DMAMUX1_CCR_DMAREQ_ID_HR_REQ6           100
#define DMAMUX1_CCR_DMAREQ_ID_DFSDM1_DMA0       101
#define DMAMUX1_CCR_DMAREQ_ID_DFSDM1_DMA1       102
#define DMAMUX1_CCR_DMAREQ_ID_DFSDM1_DMA2       103
#define DMAMUX1_CCR_DMAREQ_ID_DFSDM1_DMA3       104
#define DMAMUX1_CCR_DMAREQ_ID_TIM15_CH1         105
#define DMAMUX1_CCR_DMAREQ_ID_TIM15_UP          106
#define DMAMUX1_CCR_DMAREQ_ID_TIM15_TRIG        107
#define DMAMUX1_CCR_DMAREQ_ID_TIM15_COM         108
#define DMAMUX1_CCR_DMAREQ_ID_TIM16_CH1         109
#define DMAMUX1_CCR_DMAREQ_ID_TIM16_UP          110
#define DMAMUX1_CCR_DMAREQ_ID_TIM17_CH1         111
#define DMAMUX1_CCR_DMAREQ_ID_TIM17_UP          112
#define DMAMUX1_CCR_DMAREQ_ID_SAI3_A            113
#define DMAMUX1_CCR_DMAREQ_ID_SAI3_B            114
#define DMAMUX1_CCR_DMAREQ_ID_ADC3              115
#define DMAMUX2_CCR_DMAREQ_ID_DMAMUX2_REQ_GEN0    1
#define DMAMUX2_CCR_DMAREQ_ID_DMAMUX2_REQ_GEN1    2
#define DMAMUX2_CCR_DMAREQ_ID_DMAMUX2_REQ_GEN2    3
#define DMAMUX2_CCR_DMAREQ_ID_DMAMUX2_REQ_GEN3    4
#define DMAMUX2_CCR_DMAREQ_ID_DMAMUX2_REQ_GEN4    5
#define DMAMUX2_CCR_DMAREQ_ID_DMAMUX2_REQ_GEN5    6
#define DMAMUX2_CCR_DMAREQ_ID_DMAMUX2_REQ_GEN6    7
#define DMAMUX2_CCR_DMAREQ_ID_DMAMUX2_REQ_GEN7    8
#define DMAMUX2_CCR_DMAREQ_ID_LPUART1_RX          9
#define DMAMUX2_CCR_DMAREQ_ID_LPUART1_TX         10
#define DMAMUX2_CCR_DMAREQ_ID_SPI6_RX            11
#define DMAMUX2_CCR_DMAREQ_ID_SPI6_TX            12
#define DMAMUX2_CCR_DMAREQ_ID_I2C4_RX            13
#define DMAMUX2_CCR_DMAREQ_ID_I2C4_TX            14
#define DMAMUX2_CCR_DMAREQ_ID_SAI4_A             15
#define DMAMUX2_CCR_DMAREQ_ID_SAI4_B             16
#define DMAMUX2_CCR_DMAREQ_ID_ADC3               17

#define EXTICR1 EXTICR[0]
#define EXTICR2 EXTICR[1]
#define EXTICR3 EXTICR[2]
#define EXTICR4 EXTICR[3]

#define PriorityGroupingPreemptionBits(n)  (7-(n))

void dma_stop(DMA_Stream_TypeDef *stream);


#endif // STM32H7XX_EXTRA_H_INCLUDED
