// vectors_stm32h573xx.h
// automaically generated interrupt vector header

#ifndef VECTORS_STM32H573XX_H_INCLUDED
#define VECTORS_STM32H573XX_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

void Reset_Handler(void);
void NMI_Handler(void);
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);
void UsageFault_Handler(void);
void SecureFault_Handler(void);
void SVC_Handler(void);
void DebugMon_Handler(void);
void PendSV_Handler(void);
void SysTick_Handler(void);
void WWDG_IRQHandler(void);
void PVD_AVD_IRQHandler(void);
void RTC_IRQHandler(void);
void RTC_S_IRQHandler(void);
void TAMP_IRQHandler(void);
void RAMCFG_IRQHandler(void);
void FLASH_IRQHandler(void);
void FLASH_S_IRQHandler(void);
void GTZC_IRQHandler(void);
void RCC_IRQHandler(void);
void RCC_S_IRQHandler(void);
void EXTI0_IRQHandler(void);
void EXTI1_IRQHandler(void);
void EXTI2_IRQHandler(void);
void EXTI3_IRQHandler(void);
void EXTI4_IRQHandler(void);
void EXTI5_IRQHandler(void);
void EXTI6_IRQHandler(void);
void EXTI7_IRQHandler(void);
void EXTI8_IRQHandler(void);
void EXTI9_IRQHandler(void);
void EXTI10_IRQHandler(void);
void EXTI11_IRQHandler(void);
void EXTI12_IRQHandler(void);
void EXTI13_IRQHandler(void);
void EXTI14_IRQHandler(void);
void EXTI15_IRQHandler(void);
void GPDMA1_Channel0_IRQHandler(void);
void GPDMA1_Channel1_IRQHandler(void);
void GPDMA1_Channel2_IRQHandler(void);
void GPDMA1_Channel3_IRQHandler(void);
void GPDMA1_Channel4_IRQHandler(void);
void GPDMA1_Channel5_IRQHandler(void);
void GPDMA1_Channel6_IRQHandler(void);
void GPDMA1_Channel7_IRQHandler(void);
void IWDG_IRQHandler(void);
void SAES_IRQHandler(void);
void ADC1_IRQHandler(void);
void DAC1_IRQHandler(void);
void FDCAN1_IT0_IRQHandler(void);
void FDCAN1_IT1_IRQHandler(void);
void TIM1_BRK_IRQHandler(void);
void TIM1_UP_IRQHandler(void);
void TIM1_TRG_COM_IRQHandler(void);
void TIM1_CC_IRQHandler(void);
void TIM2_IRQHandler(void);
void TIM3_IRQHandler(void);
void TIM4_IRQHandler(void);
void TIM5_IRQHandler(void);
void TIM6_IRQHandler(void);
void TIM7_IRQHandler(void);
void I2C1_EV_IRQHandler(void);
void I2C1_ER_IRQHandler(void);
void I2C2_EV_IRQHandler(void);
void I2C2_ER_IRQHandler(void);
void SPI1_IRQHandler(void);
void SPI2_IRQHandler(void);
void SPI3_IRQHandler(void);
void USART1_IRQHandler(void);
void USART2_IRQHandler(void);
void USART3_IRQHandler(void);
void UART4_IRQHandler(void);
void UART5_IRQHandler(void);
void LPUART1_IRQHandler(void);
void LPTIM1_IRQHandler(void);
void TIM8_BRK_IRQHandler(void);
void TIM8_UP_IRQHandler(void);
void TIM8_TRG_COM_IRQHandler(void);
void TIM8_CC_IRQHandler(void);
void ADC2_IRQHandler(void);
void LPTIM2_IRQHandler(void);
void TIM15_IRQHandler(void);
void TIM16_IRQHandler(void);
void TIM17_IRQHandler(void);
void USB_DRD_FS_IRQHandler(void);
void CRS_IRQHandler(void);
void UCPD1_IRQHandler(void);
void FMC_IRQHandler(void);
void OCTOSPI1_IRQHandler(void);
void SDMMC1_IRQHandler(void);
void I2C3_EV_IRQHandler(void);
void I2C3_ER_IRQHandler(void);
void SPI4_IRQHandler(void);
void SPI5_IRQHandler(void);
void SPI6_IRQHandler(void);
void USART6_IRQHandler(void);
void USART10_IRQHandler(void);
void USART11_IRQHandler(void);
void SAI1_IRQHandler(void);
void SAI2_IRQHandler(void);
void GPDMA2_Channel0_IRQHandler(void);
void GPDMA2_Channel1_IRQHandler(void);
void GPDMA2_Channel2_IRQHandler(void);
void GPDMA2_Channel3_IRQHandler(void);
void GPDMA2_Channel4_IRQHandler(void);
void GPDMA2_Channel5_IRQHandler(void);
void GPDMA2_Channel6_IRQHandler(void);
void GPDMA2_Channel7_IRQHandler(void);
void UART7_IRQHandler(void);
void UART8_IRQHandler(void);
void UART9_IRQHandler(void);
void UART12_IRQHandler(void);
void SDMMC2_IRQHandler(void);
void FPU_IRQHandler(void);
void ICACHE_IRQHandler(void);
void DCACHE1_IRQHandler(void);
void ETH_IRQHandler(void);
void ETH_WKUP_IRQHandler(void);
void DCMI_PSSI_IRQHandler(void);
void FDCAN2_IT0_IRQHandler(void);
void FDCAN2_IT1_IRQHandler(void);
void CORDIC_IRQHandler(void);
void FMAC_IRQHandler(void);
void DTS_IRQHandler(void);
void RNG_IRQHandler(void);
void OTFDEC1_IRQHandler(void);
void AES_IRQHandler(void);
void HASH_IRQHandler(void);
void PKA_IRQHandler(void);
void CEC_IRQHandler(void);
void TIM12_IRQHandler(void);
void TIM13_IRQHandler(void);
void TIM14_IRQHandler(void);
void I3C1_EV_IRQHandler(void);
void I3C1_ER_IRQHandler(void);
void I2C4_EV_IRQHandler(void);
void I2C4_ER_IRQHandler(void);
void LPTIM3_IRQHandler(void);
void LPTIM4_IRQHandler(void);
void LPTIM5_IRQHandler(void);
void LPTIM6_IRQHandler(void);

#ifdef __cplusplus
}
#endif

#endif // VECTORS_STM32H573XX_H_INCLUDED
