#! /bin/bash -e

# erase_stm32f4_swd_srst.sh
# PUBLIC DOMAIN
# https://www.purposeful.co.uk/goodmicro/


# I, Tom Vajzovic, am the author of this software and its documentation.
# I permanently abandon all copyright and other intellectual property rights
# in them.
#
# I am fairly certain that the software does what the documentation says it
# does, but I do not guarantee that it does, or that it does what you think it
# should.  I do not guarantee that it will not have undesirable side effects.
#
# If you use, modify or distribute this software then you do so at your own
# risk.  If you do not pass on this warning then you may be responsible for any
# problems encountered by those who obtain the software through you.


this_script="$(readlink -ve "$BASH_SOURCE")"
this_script_dir="$(dirname "$this_script")"
this_script_name="$(basename "$this_script")"

if [ $# -ne 0 ]
then
  echo "$this_script_name: unexpected argument(s)" >&2
  exit 1
fi

winprog=""

if [ -x "/cygdrive/c/Program Files (x86)/STMicroelectronics/STM32 ST-LINK Utility/ST-LINK Utility/ST-LINK_CLI.exe" ]
then
  winprog="/cygdrive/c/Program Files (x86)/STMicroelectronics/STM32 ST-LINK Utility/ST-LINK Utility/ST-LINK_CLI.exe"
fi

if [ -x "/cygdrive/c/Program Files/STMicroelectronics/STM32 ST-LINK Utility/ST-LINK Utility/ST-LINK_CLI.exe" ]
then
  winprog="/cygdrive/c/Program Files/STMicroelectronics/STM32 ST-LINK Utility/ST-LINK Utility/ST-LINK_CLI.exe"
fi

if [ -n "$winprog" ]
then
  exec "$winprog" -c SWD FREQ=1800 -ME -Rst
fi

stcp_dir='/opt/st/stm32cubeide_1.6.1/plugins/com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer.linux64_1.6.0.202101291314/tools'

if [ -x $stcp_dir/bin/STM32_Programmer_CLI ]
then
  LD_LIBRARY_PATH=$stcp_dir/lib${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH-} exec $stcp_dir/bin/STM32_Programmer_CLI --connect port=SWD freq=2000 reset=SWrst mode=HOTPLUG --erase all -rst
fi

if ! which openocd >/dev/null
then
  echo $this_script_name: neither STM32_Programmer_CLI nor openocd installed >&2
  exit 1
fi

cfg="$(tempfile -s.openocd.cfg)"

trap "rm -f \"$cfg\"" EXIT

cat >"$cfg" <<EOF
#
# stlink to stm32f4xx by swd with no reset lines
#

source [find interface/stlink.cfg]

transport select hla_swd

# increase working area to 128KB
set WORKAREASIZE 0x20000

source [find target/stm32f4x.cfg]

reset_config none
EOF

openocd -f "$cfg" -c "init; reset halt; stm32f4x mass_erase 0; exit"
