#! /bin/bash -eu

logfile=$(tempfile -d. -p gdbs_ -s .log)
logfile=$(readlink -e "$logfile")

gdbs_dir='/opt/st/stm32cubeide_1.6.1/plugins/com.st.stm32cube.ide.mcu.externaltools.stlink-gdb-server.linux64_1.6.0.202101291314/tools/bin'
stcp_dir='/opt/st/stm32cubeide_1.6.1/plugins/com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer.linux64_1.6.0.202101291314/tools/bin'

cd "$gdbs_dir"

exec ./ST-LINK_gdbserver -e -f "$logfile" -l 31 -p 61234 -r 15 -k -cp "$stcp_dir" >/dev/null 2>&1
